import type { ArtifactData } from "@/model/Artifact"

// Curated from the legacy, CCBT, CBT phase 1 and CBT phase 2 descriptions.
// The currently shared artifacts retain these effect categories across versions.
// Tag benefits and enemy debuffs, not activation conditions or self penalties.
// Review this mapping when descriptions change; do not infer tags from keywords
// (e.g. spending Mana is not Mana Recovery, and a cooldown is not Cooldown Reduction).
export const ARTIFACT_EFFECT_TAGS = [
	"ATK Boost",
	"ATK Reduction",
	"ATK Spd Boost",
	"ATK Spd Reduction",
	"Accuracy",
	"Block",
	"Boss Damage",
	"Buff Dispel",
	"CC Accuracy",
	"CC Immunity",
	"CC Resistance",
	"Cleanse",
	"Cooldown Reduction",
	"Crit Chance",
	"Crit DMG",
	"Crit Resistance",
	"Crowd Control",
	"DEF Boost",
	"DEF Ignore",
	"Damage Amplification",
	"Damage Boost",
	"Damage Reduction",
	"Dodge",
	"Enemy Cooldown Increase",
	"Enemy Damage Reduction",
	"Extra Damage",
	"Heal Rate Boost",
	"Healing",
	"Healing Reduction",
	"Hero Damage",
	"Mana Recovery",
	"Mana Reduction",
	"Max HP Boost",
	"Non-Hero Damage",
	"Penetration",
	"Race Bonus",
	"Shield",
	"Survival"
] as const

export type ArtifactEffectTag = (typeof ARTIFACT_EFFECT_TAGS)[number]

const tagsByName: Record<string, readonly ArtifactEffectTag[]> = {
	"Solenis' Engraving": ["DEF Boost", "Max HP Boost"],
	"Golem's Fuel": ["Non-Hero Damage", "Damage Reduction"],
	"Earth Storm": ["Mana Recovery", "Damage Amplification", "Extra Damage"],
	"Earth Protection": ["CC Immunity", "DEF Boost"],
	"Blessing of Earth": ["ATK Boost"],
	"Earth Core": ["ATK Boost", "Max HP Boost", "DEF Boost"],
	"Earth Fortress": ["Healing Reduction", "Boss Damage"],
	"Nail Ornament of the Deep": ["Boss Damage"],
	"Belt Ornament of the Deep": ["Damage Reduction", "Cleanse"],
	"Trident of the Deep": ["ATK Boost", "Crit Chance"],
	"Ring of Spirit Morph": ["Survival"],
	"Spellbound Ring of the Deep": ["ATK Reduction", "ATK Spd Reduction"],
	"Guardian Crystal of the Deep": ["DEF Boost"],
	"Abyssal Breath": ["Non-Hero Damage", "Healing"],
	"Abyssal Crown": ["ATK Boost"],
	"Abyssal Eye": ["Extra Damage", "ATK Spd Reduction", "Crowd Control"],
	"Abyssal Nail Ornament": ["Extra Damage", "DEF Ignore"],
	"Heart of the Abyss": ["ATK Boost", "ATK Reduction"],
	"Infernal Bond": ["Enemy Cooldown Increase"],
	"Otherworldly Sword": ["Damage Boost", "Crit DMG"],
	"Infernal Greatsword": ["Penetration", "Crit DMG"],
	"Infernal Whip": ["Extra Damage", "Damage Amplification"],
	"Infernal Gate": ["DEF Boost", "Damage Boost", "Non-Hero Damage"],
	"Heart Cotton Candy": ["ATK Boost"],
	"Cross Pumpkin Head": ["Max HP Boost", "Extra Damage"],
	"Angry Pumpkin Head": ["Damage Reduction", "Damage Boost"],
	"Happy Pumpkin Head": ["Healing", "Heal Rate Boost"],
	"Surprised Pumpkin Head": ["Mana Recovery", "ATK Spd Boost"],
	"Pumpkin-Stuck Evil Spirit": ["Max HP Boost", "ATK Boost"],
	"Frost Giant Mask": ["Race Bonus", "Damage Reduction"],
	"Golden Mask of Ancient King": ["Survival"],
	"Mask of Dark Elf": ["Race Bonus", "Damage Reduction"],
	"Mask of Draconic": ["Race Bonus", "Damage Reduction"],
	"Mask of Goblin": ["Race Bonus", "Damage Reduction"],
	"Mask of Harpy": ["Race Bonus", "Damage Reduction"],
	"Mask of Lizardman": ["Race Bonus", "Damage Reduction"],
	"Mask of Orc": ["Race Bonus", "Damage Reduction"],
	"Undead Mask": ["Race Bonus", "Damage Reduction"],
	"Assassin's Veil": ["Dodge", "ATK Boost"],
	"Book of the Mad": ["Damage Boost"],
	"Burning Brazier of Elf": ["Mana Recovery"],
	"Christmas Star Ornament": ["Mana Recovery", "Crit Resistance"],
	"Warm Turkey Dish": ["Max HP Boost", "Block"],
	"Well-Done Turkey Roast": ["Healing"],
	"Christmas Tree of Holy Night": ["Crit DMG"],
	"Cooling Delicacy in the Summer": ["Damage Reduction", "Mana Recovery"],
	"Crystal Music Box": ["Hero Damage"],
	"Dice of Magical Letters": ["Extra Damage"],
	"Drinking Horn of Ancient Cow": ["ATK Boost", "ATK Spd Boost"],
	"Fancy Traditional Pendant": ["Crit Chance", "Crit DMG"],
	"Fantastic Hybrid Animals": ["Non-Hero Damage", "Damage Reduction"],
	"Feather of Sacrifice": ["Damage Amplification"],
	"Golden Apple of a Goddess": ["Healing", "Cleanse"],
	"Golden Cat Statue": ["ATK Spd Boost"],
	"Insignia of Iron Conviction": ["Cleanse", "Shield", "CC Immunity"],
	"Judgment of Light Bracelet": ["Accuracy", "CC Accuracy"],
	"Kiddy Chick": ["ATK Spd Boost"],
	"Lion of Protection": ["DEF Boost", "Block"],
	"LuLu's Necklace": ["Non-Hero Damage", "Mana Recovery"],
	"Juno's Special Dessert": ["Damage Amplification"],
	"Juno's Special Vitality Stew": ["Extra Damage"],
	"Madame's Bronze Mirrors": ["Block", "Damage Reduction"],
	"Magical Flute": ["ATK Spd Boost"],
	"New Year's Fireworks": ["ATK Boost"],
	"New Year's Fanfare": ["ATK Boost"],
	"New-Type Thruster": ["Cooldown Reduction", "Mana Recovery"],
	"Orbs of Contract": ["DEF Boost"],
	"Perfume of the Queen": ["Cleanse", "ATK Spd Boost", "CC Immunity"],
	"Pocket Watch of Ancient Civilization": ["Cooldown Reduction", "ATK Spd Boost"],
	"Primer for the Heroes": ["ATK Boost", "ATK Spd Boost", "Damage Reduction"],
	"Roaring Tiger Statue": ["Extra Damage", "Crowd Control", "ATK Reduction", "ATK Spd Reduction"],
	"Sealed Chain of Ancient God": ["Crowd Control", "Buff Dispel"],
	"Solar Stone": ["Extra Damage", "Healing Reduction"],
	"Sorcerous Black Dagger": ["Mana Reduction"],
	"Soul Spring Water": ["Healing", "Mana Recovery"],
	"Talismans of Resistance": ["Cleanse", "CC Immunity"],
	"Tarot Card of Loss": ["ATK Boost"],
	"The Ancient Scope": ["Crit Chance", "Accuracy"],
	"Tome of Black Magic": ["Extra Damage", "DEF Ignore", "Mana Reduction"],
	"Vase of Sacrifice": ["Healing", "ATK Boost"],
	"Fragment of an Ancient Kingdom": ["CC Resistance", "CC Accuracy"],
	"Goddess of Glory": ["ATK Spd Boost"],
	"Master Chef's Recipe Book": ["DEF Boost", "Heal Rate Boost"],
	"Pendulum of Fantasy": ["ATK Boost"],
	"Otherworldly Radiance": ["Cleanse", "Damage Reduction", "Buff Dispel", "Crowd Control", "Mana Reduction"],
	"Ancient God King's Coin": ["ATK Boost", "Crit DMG"],
	"Amethyst Pendulum": ["Crit Resistance"],
	"Otherworldly Helm": ["Max HP Boost", "Enemy Damage Reduction"],
	"Treasure Hunt Capsule": ["Cooldown Reduction", "Non-Hero Damage"],
	"Forge Hammer MK-II": ["ATK Spd Boost"],
	"Honorary Trophy": ["ATK Boost", "Crit Chance"],
	"Honorary Medal": ["ATK Boost", "Max HP Boost", "DEF Boost"],
	"Hero's Plaque of Appreciation": ["Max HP Boost", "Crit DMG"],
	"Academic Achievement Award": ["ATK Boost", "DEF Boost"],
	"Dragon's Doomstone": ["Non-Hero Damage", "Damage Reduction"],
	"Apocalypsion's Tear": ["ATK Boost", "Crit DMG"],
}

export function getArtifactEffectTags(artifact: Pick<ArtifactData, "id">): readonly ArtifactEffectTag[] {
	return tagsByName[artifact.id.trim().replace(/[â€˜â€™]/g, "'")] ?? []
}
